# Generated by Django 6.0.7 on 2026-08-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0002_playlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='stream_url',
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Playlist',
        ),
    ]
